---
- hosts: all
  tasks:
    - include_role:
        name: domain
      when: "'dc' in group_names"
  vars_files:
    - ./group_variables/windows_template.tmpl

- hosts: windows
  strategy: free
  tasks:
    - include_role: 
        name: workstations
      when: "'workstations' in group_names"
    - include_role:
        name: dc
      when: "'dc' in group_names"
  vars_files:
    - ./group_variables/windows_template.tmpl