---
# Prepare the dc
- hosts: domaincontroller
  roles:
    - installdomain
  vars_files:
    - ./group_vars/windows_template.yml

- hosts: domaincontroller
  roles:
    -  dc
  vars_files:
    - ./group_vars/windows_template.yml

# Prepare the windows server 2019
- hosts: workstations
  roles:
    - workstations
  vars_files:
    - ./group_vars/windows_template.yml